openapi: 3.0.0
info:
  title: Product Service API AWS Course 2023/24
  version: 1.0.0
paths:
  /products:
    get:
      summary: Get list of products
      responses:
        "200":
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    description:
                      type: string
                    price:
                      type: number
        "404":
          description: Products not found

  /{productId}:
    get:
      summary: Get a product by ID
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Product details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  price:
                    type: number
        "404":
          description: Product not found
